# Generated by Django 6.1 on 2026-08-09 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domaincredential',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='domains.domain'),
        ),
    ]
